version: "2.1"
services:
  db:
    image: postgres:15
    container_name: mafia_db
    environment:
      POSTGRES_USER: ${secrets.POSTGRES_USER}
      POSTGRES_PASSWORD: ${secrets.POSTGRES_PASSWROD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mafia:
    build: .
    container_name: mafia_app
    environment:
      DB_HOST: db
      DB_NAME: postgres
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
